### ISSUE TITLE
Documentation to lower entry barrier for those new to ITIS 

### ISSUE THREAD

**Issue by TrashBirdEcology** [ropensci/ritis#16]
This may be out of the scope of ritis project goals, but as a new user to ITIS, I am having trouble retrieving records for, e.g. Class:Aves via function `ritis::itis_search`. I think this is mainly due to my insufficient knowledge of both (a) the ITIS database and (b) regex expressions (e.g., `nameWOInd:/[A-Za-z0-9]*[ ]{0,0}*/`). 

My request is to add lines to the readme and/or vignette which lower the barrier of entry to using this product, if the goal here is to lower the barrier of entry to using ITIS API. If the goal is to simply provide interface through R, then feel free to close this issue.

**Comment by sckott** [comment]
hi @TrashBirdEcology thanks for this!

definitely we want to make all of our pkgs easier to use. 

I imagine you're talking about the function `itis_search()`?  The good thing about this query interface is that it's powerful and flexible - but it also is not the easiest to use. Can you point out what are the most confusing parts/parts that could use more explanation?

note that (i think) this complex query regex thing only applies to the functions `itis_search`, `itis_facet`, `itis_group`, and `itis_highlight`

**Comment by TrashBirdEcology** [comment]
Thanks for the quick response. Indeed, apologies, I forgot to include the function! 

As mentioned above, I simply wanted to retrieve all the bird records, but couldn't figure it out. Specifically, I could not figure out how to retrieve Class:Aves. It is also not obvious (to me) how to do so from relevant [ITIS documentation](https://www.itis.gov/ws_description.html).

In your readme and vignettes, it would be helpful to include more specific examples that are not listed at the ITIS webpages or documentation, and perhaps also better describe the primary features or potential use cases of ITIS (but again, I understand this is not the responsibility of ritis so no worries here).

Further, I briefly searched ITIS documentation about what a mono- and binomial is (I assume this is one word vs. two). These are prominent on ritis readme, but are not defined, so I have no idea what it's doing. Perhaps this is something obvious for regular solr users?

In the short term, I would be grateful for a command to retrieve a table containing all class:aves... :)

**Comment by sckott** [comment]
Thanks for the clarification, will do:

- [ ] how to do a query like `Class:Aves` with `itis_search()`
- [ ] include in readme/vign more specific egs not listed on ITIS docs
- [ ] describe the primary features or potential use cases of ITIS, any drawbacks compared to others
- [ ] describe the terms mononomial and binomial

**Comment by sckott** [comment]
To clarify, you want all _species_ within Aves? Or genera? or families?

**Comment by TrashBirdEcology** [comment]
Species level records, ideally with family col, too..

*______________________________________________________*

Jessica L. Burnett (she/her)

Mendenhall Postdoctoral Fellow & Research Ecologist

US Geological Survey Science Analytics and Synthesis
<https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis>

Github <http://github.com/trashbirdecology>

ORCID: 0000-0002-0896-5099
<https://orcid.org/0000-0002-0896-5099>
*______________________________________________________*


Join the Community for Data Integration <https://www.usgs.gov/centers/cdi>! All
welcome. It's cool.

**Comment by sckott** [comment]
`ritis` doesn't have a way to drill down many taxonomic levels - `itis_search` will only get you the information for class Aves itself, not its children. but you could then use `hierarchy_down` to drill down to the immediate children (Orders) of Aves - you could do so iteratively  until you get to species, but `taxize::downstream` does it for you

```r
z <- itis_search(q = "rank:Class AND nameWOInd:Aves")
hierarchy_down(z$tsn)
```

`taxize` is probably what you want, but beware that going from class to species takes a while

```r
library(taxize)
x <- downstream("Aves", db = 'itis', downto = 'species')
```

We have a downstream fxn in taxizedb that would be much faster https://github.com/ropensci/taxizedb but its only supported for NCBI's taxonomy data for now

**Comment by sckott** [comment]
@TrashBirdEcology I just made some fixes in the `taxizedb` package. install from github: `remotes::install_github("ropensci/taxizedb")`

Download ITIS database

```r
library(taxizedb)
db_download_itis() 
```

Downloading the database will take about 3.5 minutes, but after the first run you'll have it and won't need to download again unless you want to update the database

Then run `downstream()`, which will take about 6 minutes - but there's not internet requests so there shouldn't be any weird timeouts as you get with API pkgs. 

```r
id <- name2taxid('Aves', db = "itis")
out <- taxizedb::downstream(id, db = 'itis', downto = 'species')
NROW(out[[1]])
#> [1] 10412
```

does ~10K species sound right?

let me know if that works for you

**Comment by TrashBirdEcology** [comment]
Brilliant -- thank you so much for taking the time to do this! :)

**Comment by sckott** [comment]
bummed it still takes 6 minutes, but at least that's a huge improvement over what taxize would do
